version: "3.8"
services:
  auth-service:
    build: .
    restart: always
    depends_on:
      - mysql-userdb
    networks:
      default:
        aliases:
          - rmqnet
  mysql-userdb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      default:
        aliases:
          - rmqnet

networks:
  default:
    name: rmqnet