apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-cm
data:
  url: "jdbc:mysql://userdb-service:3306/userdb"
  database: "userdb"
  username: "root"
  password: "root"
  root_password: "root"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  replicas: 1
  template:
    metadata:
      labels:
        app: userdb
      name: userdb-service
    
    spec:
      containers:
        - image: mysql:latest
          name: userdb
          ports:
            - containerPort: 3306
              name: userdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "userdb"
          volumeMounts:
            - name: userdb-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: userdb-persistent-storage
          persistentVolumeClaim:
            claimName: userdb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: userdb
  name: userdb-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: userdb
  clusterIP: None