apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-cm
data:
  url: "jdbc:mysql://userdb:3306/userdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false"
  database: "userdb"
  username: "root"
  password: "root"
  root_password: "root"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  replicas: 1
  template:
    metadata:
      labels:
        app: userdb
      name: userdb-service
    
    spec:
      containers:
        - image: mysql:latest
          name: userdb
          ports:
            - containerPort: 3306
              name: userdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: userdb-cm
                  key: root_password
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: userdb-cm
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: userdb-cm
                  key: database

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: userdb
  name: userdb-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: userdb
  clusterIP: None