### Global
server:
  port: 9898
### End Global

### Kubernetes
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    validationQuery: SELECT 1
    initialize-model: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
### End Kubernetes

### Local
#spring:
#  application:
#    name: AUTH-SERVICE
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
### End Local